# https://www.codewars.com/kata/5a331ea7ee1aae8f24000175/train/ruby

# Disclaimer

# This Kata is an insane step-up from Avanta's Kata, so I recommend to solve it first before trying this one.

# Problem Description

# A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

# For example, different possibilities are:

# Colour here:            G G        B G        R G        B R
# Becomes colour here:     G          R          B          G
# With a bigger example:

# R R G B R G B B
#  R B R G B R B
#   G G B R G G
#    G R G B G
#     B B R R
#      B G R
#       R B
#        G
# You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would be given 'RRGBRGBB', and you should return 'G'.

# Constraints

# 1 <= length(row) <= 10 ** 5

# The input string will only contain the uppercase letters 'B', 'G' or 'R'.

# The exact number of test cases will be as follows:

# 100 tests of 100 <= length(row) <= 1000
# 100 tests of 1000 <= length(row) <= 10000
# 100 tests of 10000 <= length(row) <= 100000
# Examples

# triangle('B') == 'B'
# triangle('GB') == 'R'
# triangle('RRR') == 'R'
# triangle('RGBG') == 'B'
# triangle('RBRGBRB') == 'G'
# triangle('RBRGBRBGGRRRBGBBBGG') == 'G'

require 'benchmark'

def int2chr(no)
  return 'R' if no == 0
  return 'G' if no == 1
  return 'B' if no == 2
  'e' # shouldn't happen
end

def char2int(chr)
  return 0 if chr == 'R'
  return 1 if chr == 'G'
  return 2 if chr == 'B'
  -1 # shouldn't happen
end

def evalPair(ch1, ch2)
  ch1 = char2int(ch1) if ch1.class == String
  ch2 = char2int(ch2) if ch2.class == String
  ch1 == ch2 ? ch1 : (-ch1 - ch2) % 3
end

def insane(str)
  return str if str.length == 1

  # https://www.researchgate.net/publication/259609261_The_three-color_triangle_problem
  sub = str.chars
  until sub.length == 1
    nsub = []
    gap = 3**(Math.log(sub.length-1, 3).to_i)
    pointer = 0
    until pointer+gap == sub.length
      nsub.push( evalPair(sub[pointer+gap], sub[pointer]) )
      pointer += 1
    end
    sub = nsub
  end  
  int2chr(sub.first)
end

str = File.read('string.rb')
p str.length
time = Benchmark.measure {
  p insane('B')
  p insane('GB')
  p insane('RRR')
  p insane('RGBG')
  p insane('RBRGBRB')
  p insane('RBRGBRBGGRRRBGBBBGG')
  p insane(str)
}
puts time